name: CowCannon
version: '1.0'
main: com.Helloy.cowCannon.CowCannon
description: A plugin that blows up certain cows upon right clicking them!
author: Hihelloy
api-version: '1.20'
folia-supported: true

commands:
  cow:
    description: Spawn an exploding cow
    usage: /cow [baby]
    aliases:
      - cowcannon
    permission: cowcannon.command.cow
    permission-message: You do not have permission to use this command

permissions:
  cowcannon.command.cow:
    description: Allows use of the /cow command
    default: op
    children:
      cowcannon.cow.use: true

  cowcannon.cow.use:
    description: Allows right-clicking cows to blow them up
    default: false
